server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: root
    password: root

  hibernate:
    ddl-aut: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
